### ISSUE TITLE
Same weights for different attention mechanisms?

### ISSUE THREAD

**Issue by pwrose** [ZihanWangKi/XClass#4]
https://github.com/ZihanWangKi/XClass/blob/main/scripts/class_oriented_document_representations.py#L95-L100

In the following statements, the weights are all the same. Is this intended?

    elif attention_mechanism == "relation":
        weights = weights_from_ranking(relation_ranking)
    elif attention_mechanism == "significance_static":
        weights = weights_from_ranking(relation_ranking)
    elif attention_mechanism == "relation_static":
        weights = weights_from_ranking(relation_ranking)

**Comment by ZihanWangKi** [comment]
Hi,
This is definitely a mistake. Thanks for pointing it out. I made a fix in this [branch](https://github.com/ZihanWangKi/XClass/blob/16ccf52bf3d41d08b586d241d87343cc8132d4eb/scripts/class_oriented_document_representations.py#L93), but I haven't tested out some other details so it isn't merged yet. Meanwhile, if you want to experiment with different mechanisms (instead of the default mixture one), you can copy the changes there.
Hope this helps!
